# Stage 1 - frontend
FROM debian:bookworm as buildFrontend

RUN apt-get update && apt-get install -y \
	openssh-client \
	bash \
	ca-certificates \
	git \
	curl \
	sudo \
	nodejs \
	npm \
	&& update-ca-certificates \
	&& rm -rf /var/lib/apt/lists/*

RUN npm install --global yarn 
RUN ssh-keyscan github.com >> ~/.ssh/known_hosts
ADD ../frontend /source
WORKDIR /source
RUN ls -lR
RUN yarn install && yarn build

# Stage 2 - api & web server
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS buildBackend

# Add packages we need.
RUN apt-get update && apt-get install -y \
	openssh-client \
	bash \
	ca-certificates \
	git \
	&& update-ca-certificates \
	&& rm -rf /var/lib/apt/lists/*

ADD ../backend /source
WORKDIR /source
RUN ls -la

RUN rm /source/AnanaPhone/wwwroot/index.html
COPY --from=buildFrontend /source/dist .

WORKDIR /source/backend/AnanaPhone
RUN dotnet restore && dotnet publish --output /app --configuration Debug

# STAGE 3 - Package
FROM mcr.microsoft.com/dotnet/aspnet:7.0

RUN mkdir -p /vmail
VOLUME /vmail
# sip
EXPOSE 5060/udp
EXPOSE 5060/tcp
# rtp
EXPOSE 5100-5200/udp
EXPOSE 5100-5200/tcp
# ami
EXPOSE 5038/tcp

# SSHD
EXPOSE 5039/tcp

RUN apt-get update && apt-get install -y \
	openssh-client \
	bash \
	curl \
	cron \
	sudo \
	asterisk \
	htop \
	sngrep \
	dos2unix \
	iproute2 \
	inetutils-ping \
	nano \
	wget \
	openssh-server \
	&& rm -rf /var/lib/apt/lists/*

RUN rm -rf /etc/asterisk/ && \
	mkdir -p /etc/asterisk/_holdmusic

# Setup SSHD
COPY includes/sshd/sshd_config /etc/ssh/sshd_config
RUN mkdir -p /root/.ssh/
COPY includes/sshd/authorized_keys /root/.ssh/authorized_keys
RUN dos2unix /etc/ssh/sshd_config \
	&& dos2unix /root/.ssh/authorized_keys \
	&& chmod 600 /root/.ssh/authorized_keys \
	&& chmod 700 /root/.ssh

# Setup Cron
COPY includes/cron/cron15min.sh /cron15min.sh
COPY includes/cron/cronDaily.sh /cronDaily.sh
COPY includes/cron/cronHourly.sh /cronHourly.sh
COPY includes/cron/cronMonthly.sh /cronMonthly.sh
COPY includes/cron/cronWeekly.sh /cronWeekly.sh
COPY includes/cron/crontab.txt /crontab.txt
COPY includes/entry.sh /entry.sh

RUN dos2unix /cron15min.sh /cronDaily.sh /cronHourly.sh /cronMonthly.sh /cronWeekly.sh /entry.sh && \
	chmod 755 /cron15min.sh /cronDaily.sh /cronHourly.sh /cronMonthly.sh /cronWeekly.sh /entry.sh && \
	dos2unix /crontab.txt && crontab /crontab.txt

# Configure Asterisk
COPY includes/asterisk/ /etc/asterisk/
RUN dos2unix /etc/asterisk/* && \
	dos2unix /etc/asterisk/extensions.d/* && \
	dos2unix /etc/asterisk/manager.d/* && \
	dos2unix /etc/asterisk/pjsip_wizard.d/*

CMD ["/entry.sh"]