#docker build --no-cache --progress=plain -f dockerfile.txt ../
version: '2.0'
services:
  ananaphone:
    build:
      context: ../
      dockerfile: ./docker/dockerfile.txt
    container_name: ananaphone
    image: maskawanian/ananaphone:latest
    restart: always
    volumes:
      - ./secrets:/secrets
      - ./data-vmail:/vmail
      - ./data-database:/database
      - ./data-holdmusic:/holdmusic
      - ./data-recordings:/recordings
    network_mode: host
    environment:
     - TZ=America/Winnipeg
     - ASPNETCORE_ENVIRONMENT=Development
     - ASTERISK_HOST_FILE=/secrets/ASTERISK_HOST.txt
     - ASTERISK_AMI_PORT_FILE=/secrets/ASTERISK_AMI_PORT.txt
     - ASTERISK_AMI_USER_FILE=/secrets/ASTERISK_AMI_USER.txt
     - ASTERISK_AMI_PASS_FILE=/secrets/ASTERISK_AMI_PASS.txt
     - ASTERISK_SIP_PORT_FILE=/secrets/ASTERISK_SIP_PORT.txt
     - SQLITE_DATABASE_DIRECTORY=/database
     - S3_ACCESS_KEY_FILE=/secrets/S3_ACCESS_KEY.txt
     - S3_SECRET_KEY_FILE=/secrets/S3_SECRET_KEY.txt
     - S3_FORCE_PATH_STYLE=true
     - S3_SERVICE_URI_FILE=/secrets/S3_SERVICE_URI.txt
     - VMAIL_S3_BUCKET=vmail
     - ASTERISK_DEBUG_SSH_PORT_FILE=/secrets/ASTERISK_DEBUG_SSH_PORT.txt
     - ASTERISK_DEBUG_SSH_USER_FILE=/secrets/ASTERISK_DEBUG_SSH_USER.txt
     #- ASTERISK_DEBUG_SSH_ENABLE=true # debug
     - ASTERISK_DEBUG_SSH_ENABLE=false
     #- AMI_PW=aaa # debug
     - ASTERISK_EXTERNAL_IP_ADDRESS_FILE=/secrets/ASTERISK_EXTERNAL_IP_ADDRESS.txt
     - NODE_ENV=development
     - VITE_NODE_ENV=development
     - ASTERISK_HOME_AREA_CODE=204
     - ASTERISK_RECORDINGS_DIRECTORY=/recordings
     - ASTERISK_AGI_HOST_FILE=/secrets/ASTERISK_AGI_HOST.txt
     #- ASTERISK_AGI_HOST_FILE=/secrets/ASTERISK_AGI_HOST_DEBUG.txt # debug
     - GENERATE_ASTERISK_CONFIG=true
     - SEEK_OWNER_FROM_E164=
  ananaphone-minio:
    image: minio/minio
    container_name: ananaphone-minio
    ports:
     - "5205:5205" # access
     - "5204:5204" # console
    volumes:
     - ./data-minio:/data
     - ./secrets:/secrets
    environment:
     - TZ=America/Winnipeg
     # https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#configuration-settings
     - MINIO_CONFIG_ENV_FILE=/secrets/MINIO_CONFIG_ENV_FILE.txt
    restart: always
    command: server --address ":5205" --console-address ":5204" /data