version: '2.0'
services:
  ananaphone:
    build:
      context: ../
      dockerfile: ./dockerfile.txt
    container_name: ananaphone
    restart: always
    volumes:
      - ./secrets:/var/run/secrets
      - ./data-vmail:/vmail
    ports:
     - '5060:5060/udp' # sip
     - '5060:5060/tcp' # sip
     - '5100-5200:5100-5200/udp' # rtp
     - '5100-5200:5100-5200/tcp' # rtp
     - '5038:5038/tcp' # ami
     - '5039:5039/tcp' # sshd
    environment:
     - TZ=America/Winnipeg
    networks:
     - ananaphone
  ananaphone-minio:
    image: minio/minio
    container_name: ananaphone-minio
    ports:
     - "15003:15003" # access
     - "15004:15004" # console
    volumes:
     - ./data-minio:/data
     - ./secrets:/var/run/secrets
    environment:
     - TZ=America/Winnipeg
     # https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#configuration-settings
     - MINIO_CONFIG_ENV_FILE=/var/run/secrets/MINIO_CONFIG_ENV_FILE.txt
    restart: always
    command: server --address ":15003" --console-address ":15004" /data
    networks:
      - ananaphone
networks:
  ananaphone:
    name: ananaphone
