# Stage 1 - frontend
FROM maskawanian/debian-node-build:bookworm as buildFrontend
ADD ./frontend /source
WORKDIR /source
#RUN ls -lR
RUN yarn install && yarn build

# Stage 2 - api & web server
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS buildBackend

# Add packages we need.
RUN apt-get update && apt-get install -y \
	bash \
	&& rm -rf /var/lib/apt/lists/*
RUN mkdir -p /app
ADD ./backend /source
WORKDIR /source
RUN rm /source/AnanaPhone/wwwroot/index.html
WORKDIR /source/AnanaPhone/wwwroot
COPY --from=buildFrontend /source/dist .

RUN ls -la
WORKDIR /source/AnanaPhone
RUN dotnet restore && dotnet publish --output /app --configuration Debug

WORKDIR /app
RUN ls -laR

# STAGE 3 - Package
FROM maskawanian/dotnet-aspnet-asterisk:7.0 as final

# http
EXPOSE 80/tcp

# SIP
EXPOSE 5060/udp
EXPOSE 5060/tcp

# RTP
EXPOSE 5100-5200/udp
EXPOSE 5100-5200/tcp

# AMI
EXPOSE 5038/tcp

# SSHD
EXPOSE 5039/tcp

# Data Protection Keys
VOLUME /root/.aspnet/DataProtection-Keys

RUN mkdir -p /vmail && mkdir -p /app
VOLUME /vmail

COPY --from=buildBackend /app /app

# Copy over hold music.
COPY docker/includes/holdmusic /holdmusic

# Setup SSHD
COPY docker/includes/sshd/sshd_config /etc/ssh/sshd_config
RUN mkdir -p /root/.ssh/
COPY docker/includes/sshd/authorized_keys /root/.ssh/authorized_keys
RUN dos2unix /etc/ssh/sshd_config \
	&& dos2unix /root/.ssh/authorized_keys \
	&& chmod 600 /root/.ssh/authorized_keys \
	&& chmod 700 /root/.ssh

# Setup Cron
COPY docker/includes/cron/cron15min.sh /cron15min.sh
COPY docker/includes/cron/cronDaily.sh /cronDaily.sh
COPY docker/includes/cron/cronHourly.sh /cronHourly.sh
COPY docker/includes/cron/cronMonthly.sh /cronMonthly.sh
COPY docker/includes/cron/cronWeekly.sh /cronWeekly.sh
COPY docker/includes/cron/crontab.txt /crontab.txt
COPY docker/includes/entry.sh /entry.sh

RUN dos2unix /cron15min.sh /cronDaily.sh /cronHourly.sh /cronMonthly.sh /cronWeekly.sh /entry.sh && \
	chmod 755 /cron15min.sh /cronDaily.sh /cronHourly.sh /cronMonthly.sh /cronWeekly.sh /entry.sh && \
	dos2unix /crontab.txt && crontab /crontab.txt

# Configure Asterisk
RUN rm -rf /etc/asterisk/
COPY docker/includes/asterisk/ /etc/asterisk/
RUN dos2unix /etc/asterisk/* && \
	dos2unix /etc/asterisk/extensions.d/* && \
	dos2unix /etc/asterisk/manager.d/* && \
	dos2unix /etc/asterisk/pjsip_wizard.d/*




CMD ["/entry.sh"]